import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import { getDialect, DIALECT_NAMES } from '../../src/db/dialect.js';

describe('dialect — 逻辑类型到各数据库原生类型的映射', () => {
  test('支持四种数据库', () => {
    assert.deepEqual([...DIALECT_NAMES].sort(), ['mssql', 'mysql', 'pg', 'sqlite']);
  });

  test('未知数据库类型抛错', () => {
    assert.throws(() => getDialect('oracle'), /数据库类型/);
  });

  describe('金额一律映射为整数类型（以分存储）', () => {
    test('四种数据库的 {{MONEY}} 都是整数家族，绝不使用 DECIMAL/FLOAT', () => {
      for (const name of DIALECT_NAMES) {
        const sql = getDialect(name).expandDdl('amount {{MONEY}}');
        assert.doesNotMatch(sql, /DECIMAL|NUMERIC|FLOAT|DOUBLE|REAL/i, `${name} 不应使用浮点/定点类型`);
        assert.match(sql, /INT/i, `${name} 的金额应为整数类型`);
      }
    });
  });

  describe('主键映射', () => {
    test('sqlite 用 INTEGER PRIMARY KEY AUTOINCREMENT（即 rowid 别名）', () => {
      assert.equal(getDialect('sqlite').expandDdl('id {{PK}}'), 'id INTEGER PRIMARY KEY AUTOINCREMENT');
    });

    test('pg 用 IDENTITY', () => {
      assert.match(getDialect('pg').expandDdl('id {{PK}}'), /GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/);
    });

    test('mssql 用 IDENTITY(1,1)', () => {
      assert.match(getDialect('mssql').expandDdl('id {{PK}}'), /IDENTITY\(1,1\) PRIMARY KEY/);
    });

    test('mysql 用 AUTO_INCREMENT', () => {
      assert.match(getDialect('mysql').expandDdl('id {{PK}}'), /AUTO_INCREMENT PRIMARY KEY/);
    });
  });

  describe('文本类型', () => {
    test('mssql 使用 NVARCHAR 以支持中文', () => {
      assert.match(getDialect('mssql').expandDdl('name {{TEXT}}'), /NVARCHAR/);
    });

    test('sqlite 使用 TEXT', () => {
      assert.equal(getDialect('sqlite').expandDdl('name {{TEXT}}'), 'name TEXT');
    });

    test('{{LONGTEXT}} 在 mssql 为 NVARCHAR(MAX)', () => {
      assert.match(getDialect('mssql').expandDdl('body {{LONGTEXT}}'), /NVARCHAR\(MAX\)/);
    });
  });

  describe('时间类型', () => {
    test('pg 使用不带时区的 TIMESTAMP（避免中国时区整体偏移）', () => {
      const sql = getDialect('pg').expandDdl('at {{DATETIME}}');
      assert.match(sql, /TIMESTAMP/);
      assert.doesNotMatch(sql, /TIMESTAMPTZ|WITH TIME ZONE/i);
    });

    test('sqlite 时间存 TEXT 字符串', () => {
      assert.equal(getDialect('sqlite').expandDdl('at {{DATETIME}}'), 'at TEXT');
    });

    test('mssql 使用 DATETIME2', () => {
      assert.match(getDialect('mssql').expandDdl('at {{DATETIME}}'), /DATETIME2/);
    });
  });

  describe('expandDdl 整体替换', () => {
    test('一次替换多个标记', () => {
      const ddl = `create table t (
        id {{PK}},
        name {{TEXT}} not null,
        amount {{MONEY}},
        at {{DATETIME}}
      )`;
      const out = getDialect('sqlite').expandDdl(ddl);
      assert.doesNotMatch(out, /\{\{/, '不应残留未替换的标记');
      assert.match(out, /id INTEGER PRIMARY KEY AUTOINCREMENT/);
      assert.match(out, /amount INTEGER/);
    });

    test('未识别的标记抛错，避免静默产出坏 DDL', () => {
      assert.throws(() => getDialect('sqlite').expandDdl('x {{NOPE}}'), /未知的类型标记/);
    });
  });

  describe('能力标记', () => {
    test('sqlite 与 pg 支持 RETURNING，mysql 不支持', () => {
      assert.equal(getDialect('sqlite').capabilities.returning, true);
      assert.equal(getDialect('pg').capabilities.returning, true);
      assert.equal(getDialect('mysql').capabilities.returning, false);
    });

    test('全部数据库都支持 SAVEPOINT 嵌套事务', () => {
      for (const name of DIALECT_NAMES) {
        assert.equal(getDialect(name).capabilities.savepoint, true, name);
      }
    });

    test('全部数据库都需要显式开启外键约束设置（sqlite 需 PRAGMA）', () => {
      assert.equal(getDialect('sqlite').capabilities.foreignKeysPragma, true);
      assert.equal(getDialect('pg').capabilities.foreignKeysPragma, false);
    });
  });
});
