/**
 * 数据库方言：把业务/迁移代码里的逻辑类型标记展开为各数据库的原生类型。
 *
 * 迁移脚本用 {{PK}} / {{TEXT}} / {{MONEY}} 这类标记书写，
 * 于是同一份建表语句能在 SQLite / MySQL / PostgreSQL / SQL Server 上运行，
 * 满足需求书 8.2「切换数据库后无需修改业务代码」。
 */

import { ConfigError } from '../core/errors.js';

/**
 * 关键决策：金额在四种数据库里一律用整数类型。
 * 系统内部以「分」为单位存储金额，因此不需要 DECIMAL，也就彻底避开了
 * 各数据库定点数行为差异与浮点误差。
 */
const TYPE_TOKENS = {
  sqlite: {
    PK: 'INTEGER PRIMARY KEY AUTOINCREMENT',
    FK: 'INTEGER',
    TEXT: 'TEXT',
    LONGTEXT: 'TEXT',
    INT: 'INTEGER',
    MONEY: 'INTEGER',
    DATETIME: 'TEXT',
    DATE: 'TEXT',
    BOOL: 'INTEGER',
  },
  mysql: {
    PK: 'BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY',
    FK: 'BIGINT',
    TEXT: 'VARCHAR(255)',
    LONGTEXT: 'TEXT',
    INT: 'INT',
    MONEY: 'BIGINT',
    DATETIME: 'DATETIME',
    DATE: 'DATE',
    BOOL: 'TINYINT(1)',
  },
  pg: {
    PK: 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
    FK: 'BIGINT',
    TEXT: 'VARCHAR(255)',
    LONGTEXT: 'TEXT',
    INT: 'INTEGER',
    MONEY: 'BIGINT',
    // 刻意使用不带时区的 TIMESTAMP：带时区会让中国本地时间整体偏移
    DATETIME: 'TIMESTAMP',
    DATE: 'DATE',
    BOOL: 'BOOLEAN',
  },
  mssql: {
    PK: 'BIGINT IDENTITY(1,1) PRIMARY KEY',
    FK: 'BIGINT',
    TEXT: 'NVARCHAR(255)',
    LONGTEXT: 'NVARCHAR(MAX)',
    INT: 'INT',
    MONEY: 'BIGINT',
    DATETIME: 'DATETIME2',
    DATE: 'DATE',
    BOOL: 'BIT',
  },
};

/** 各数据库的能力差异，供上层决定取回自增主键的方式等。 */
const CAPABILITIES = {
  sqlite: { returning: true, savepoint: true, foreignKeysPragma: true, multiStatement: true },
  mysql: { returning: false, savepoint: true, foreignKeysPragma: false, multiStatement: false },
  pg: { returning: true, savepoint: true, foreignKeysPragma: false, multiStatement: true },
  mssql: { returning: false, savepoint: true, foreignKeysPragma: false, multiStatement: false },
};

/** 驱动包名，仅在选择该数据库时才动态加载，默认路径零依赖。 */
const DRIVER_PACKAGES = {
  sqlite: null, // node:sqlite 是 Node 内置模块，无需安装
  mysql: 'mysql2',
  pg: 'pg',
  mssql: 'mssql',
};

export const DIALECT_NAMES = Object.freeze(Object.keys(TYPE_TOKENS));

export class Dialect {
  constructor(name) {
    this.name = name;
    this.types = TYPE_TOKENS[name];
    this.capabilities = CAPABILITIES[name];
    this.driverPackage = DRIVER_PACKAGES[name];
  }

  /** 把 DDL 中的 {{TOKEN}} 展开为原生类型；遇到未知标记直接抛错，避免产出坏语句。 */
  expandDdl(sql) {
    return sql.replace(/\{\{([A-Z_]+)\}\}/g, (whole, token) => {
      const mapped = this.types[token];
      if (mapped === undefined) {
        throw new ConfigError(`未知的类型标记 ${whole}（数据库：${this.name}）`);
      }
      return mapped;
    });
  }
}

const CACHE = new Map();

export function getDialect(name) {
  if (!TYPE_TOKENS[name]) {
    throw new ConfigError(`不支持的数据库类型：${name}（可选：${DIALECT_NAMES.join(' / ')}）`);
  }
  if (!CACHE.has(name)) CACHE.set(name, new Dialect(name));
  return CACHE.get(name);
}
